# Generated by Django 6.0 on 2026-01-20 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_best_seller',
            field=models.BooleanField(default=False),
        ),
    ]
