# Generated by Django 6.0 on 2026-01-20 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_is_best_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='includes',
            field=models.TextField(blank=True, default='', help_text='Enter one item per line (e.g. Deep dusting, Floor cleaning, etc.)'),
        ),
    ]
