# Generated by Django 6.0 on 2026-01-27 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_worker_email_worker_experiance_years_worker_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='role',
            field=models.CharField(choices=[('cleaning expert', 'Cleaning Expert'), ('appliance_technician', 'Appliance Technician'), ('electrician', 'Electrician'), ('plumber', 'Plumber'), ('beautician', 'Beautician'), ('painter', 'Painter')], max_length=100),
        ),
    ]
