# Generated by Django 6.0 on 2026-02-25 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_alter_servicecategory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='services',
            field=models.ManyToManyField(related_name='workers', to='services.service'),
        ),
    ]
