# Generated by Django 6.0 on 2026-02-25 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_worker_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='role',
        ),
    ]
