# Generated by Django 6.0 on 2026-03-10 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_alter_service_duration_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='color',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
