# Generated by Django 6.0 on 2026-03-10 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_servicecategory_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='icon_color',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
