# Generated by Django 6.0 on 2026-02-11 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_paymet'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Paymet',
            new_name='Payment',
        ),
    ]
