# Generated by Django 6.0 on 2026-02-19 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_payment_paid_at_payment_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='label',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
