# Generated by Django 6.0 on 2026-03-06 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
